name: Snyk Security Scan

on:
  push:
    branches: [master]
  pull_request:

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Authenticate Snyk
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth $SNYK_TOKEN

    - name: Run Snyk Scan (SCA and SAST)
      run: snyk test --severity-threshold=high --json-file-output=snyk-report.json

    - name: Monitor Snyk Project (Upload to Dashboard)
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk monitor --all-projects

    - name: Upload report artifact
      uses: actions/upload-artifact@v4
      with:
        name: snyk-report
        path: snyk-report.json
